spring.application.name=demo-spring

# Banco H2 (novo nome)
spring.datasource.url=jdbc:h2:mem:demo_spring
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true